### ISSUE TITLE
Cannot register LaunchAgent

### ISSUE THREAD

**Issue by tonekk** [typicode/hotel#101]
When starting hotel, I get:

`/Users/finn/Library/LaunchAgents/hotel.plist: Operation not permitted`

When visiting `http://localhost:2000` , I get:

<img width="572" alt="screen shot 2016-05-06 at 10 39 27 am" src="https://cloud.githubusercontent.com/assets/3327396/15068349/e5a38b74-1376-11e6-9c26-b4fbd02800c4.png">

**Comment by typicode** [comment]
Hi @tonekk,

Thank you for reporting, this is the first time I see this issue, so it would be helpful if you could you run a few commands and paste the output?

`ls -la /Users/finn/Library/LaunchAgents/` to check `hotel.plist` permissions.
`cat /Users/finn/Library/LaunchAgents/hotel.plist` to check that everything points to the correct path.

And could you get the output of `~/.hotel/daemon.log` also, there should be some errors just after you run `hotel start`.

Finally, it would be interesting to run manually `launchctl load /Users/finn/Library/LaunchAgents/hotel.plist` (this is what `hotel start` does).

I suspect there might be some permissions issues.

**Comment by typicode** [comment]
Closing it. Feel free to open it again if you still have the issue.

**Comment by clekstro** [comment]
@typicode Got the same thing on a clean install.  I found that if I open a new terminal tab, the command runs w/o issue.

**Comment by typicode** [comment]
Hi @clekstro,

Thanks for the report, I don't really know why it's happening and it's strange that it works with a new tab.
Do you use `sudo` at some point like `sudo npm install hotel -g`?

I wonder if it's related to some rights issues or the content of the `.plist` file. If you get the issue again, could you run:

```sh
ls -la ~/Library/LaunchAgents/
cat ~/Library/LaunchAgents/hotel.plist
```

**Comment by tnguyen14** [comment]
@typicode I am running into this exact issue as well. Here's the permission for the `.plist` file

```
-rw-r--r--  1 tnguyen staff         586 Aug 25 22:08 hotel.plist
```

Here's the content of the file

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>hotel</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/node</string>
    <string>/usr/local/lib/node_modules/hotel/lib/daemon</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/Users/tnguyen/.hotel/daemon.log</string>
  <key>StandardErrorPath</key>
  <string>/Users/tnguyen/.hotel/daemon.log</string>
</dict>
</plist>
```

Starting it on a new tab gives me localhost:2000 working, but `hotel.dev` is still not working.

**Comment by posva** [comment]
This is related to tmux. You have to start hotel on another terminal

**Comment by DigitallyBorn** [comment]
I'm not using tmux and am getting the same issue.

```sh
bash-3.2$ npm install -g hotel && hotel start

> hotel@0.7.3 uninstall /usr/local/lib/node_modules/hotel
> node bin/uninstall.js

/usr/local/bin/hotel -> /usr/local/lib/node_modules/hotel/lib/cli/bin.js
/usr/local/lib
└── hotel@0.7.3 

/usr/local/lib/node_modules/hotel/node_modules/yargs/yargs.js:1078
      else throw err
           ^

Error: EACCES: permission denied, open '/Users/rickysmith/Library/LaunchAgents/hotel.plist'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at add (/usr/local/lib/node_modules/hotel/node_modules/user-startup/lib/startup/darwin.js:43:6)
    at Object.create (/usr/local/lib/node_modules/hotel/node_modules/user-startup/lib/startup/darwin.js:51:14)
    at Object.start (/usr/local/lib/node_modules/hotel/lib/cli/daemon.js:22:11)
    at Object.handler (/usr/local/lib/node_modules/hotel/lib/cli/index.js:77:19)
    at Object.self.runCommand (/usr/local/lib/node_modules/hotel/node_modules/yargs/lib/command.js:231:22)
    at Object.Yargs.self._parseArgs (/usr/local/lib/node_modules/hotel/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/hotel/node_modules/yargs/yargs.js:930:19)
    at module.exports (/usr/local/lib/node_modules/hotel/lib/cli/index.js:80:467)
```

The `hotel.plist` file does not exist in `~/Library/LaunchAgents/`

**Comment by DigitallyBorn** [comment]
In my case, my local user didn't own `~/Library/LaunchAgents`. 

The fix: `sudo chown `whoami` /Users/`whoami`/Library/LaunchAgents`

**Comment by zhaozhiming** [comment]
Same problem to me.
