### ISSUE TITLE
CLI should support multiple environment variables

### ISSUE THREAD

**Issue by aleclarson** [typicode/hotel#103]
It would be nice if `hotel add -e` supported multiple environment variables.

`hotel add -e FOO BAR`

https://github.com/typicode/hotel/blob/master/src/cli/servers.js#L49-L51

**Comment by typicode** [comment]
Hi,

I agree :) this would improve hotel.
If you want you can make a PR + quick test in https://github.com/typicode/hotel/blob/master/test/cli/servers.js

**Comment by typicode** [comment]
Should be good in next release:

```sh
hotel add 'npm start' --env ENV_A ENV_B ENV_C
```
