### ISSUE TITLE
Allow empty lines in Output.vue

### ISSUE THREAD

**Issue by aleclarson** [typicode/hotel#104]
I'd like to preserve empty lines in the web interface. Any ideas?

**Comment by typicode** [comment]
It's a bug. I'm refactoring the UI so I'm adding this to the TODO list.

**Comment by typicode** [comment]
It should be good in `v0.5.0` beta. For the moment, it's only available using the following command `npm install -g hotel@next` (`README` is in the `next` branch)

I'd like to get user feedbacks before making it available to everyone. If you install it let me know if it works for you or if you find some issues :)

**Comment by typicode** [comment]
There's an issue with the beta preventing creating new servers: https://github.com/typicode/hotel/issues/102

**Comment by typicode** [comment]
Just released `v0.5.0`, should be good now :)
