### ISSUE TITLE
`curl hotel.dev` hangs

### ISSUE THREAD

**Issue by tonytonyjan** [typicode/hotel#106]
I have set automatic proxy configuration to `http://localhost:2000/proxy.pac`.

![](https://i.imgur.com/sZKJ1ag.png)

It works well in Google Chrome, however, hangs in terminal using either `curl` or `httpie`. Did I miss anything?

**Comment by prashnts** [comment]
In case others are wondering, terminal does not use proxy `pac` configuration. To configure proxy in your session, you must set `http_proxy` environment variable.

I use aliased `httpie` as `alias httpdev="http_proxy='http://localhost:2000/proxy.pac' http"` so I can use `httpdev ...` in place of `http ...`.
