### ISSUE TITLE
Cannot start hotel 0.5.3

### ISSUE THREAD

**Issue by nghuuphuoc** [typicode/hotel#110]
Here is what I got after running `hotel start`:

```
/usr/local/lib/node_modules/hotel/bin/index.js:7
updateNotifier({ pkg }).notify()
                     ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by typicode** [comment]
Hi,

Thank you for the report. It's a bug, index.js should only use ES5 syntax.

I'm on vacation right now, so please use the previous version for the moment (npm i -g hotel@0.5.2)

**Comment by hyperh** [comment]
0.5.2 still doesn't work for me. I get the same error as @nghuuphuoc.

**Comment by hyperh** [comment]
Looking at the tagged commits, it seems like only pre-0.5.0 works.

`0.5.0-beta.5` is the first commit without that ES6 syntax.
https://github.com/typicode/hotel/blob/v0.5.0-beta.5/bin/index.js

**Comment by nghuuphuoc** [comment]
You're right. My current workaround is to comment the line of `updateNotifier({ pkg }).notify()` in `index.js`.

**Comment by hyperh** [comment]
@nghuuphuoc I just did 
```
updateNotifier({ pkg: pkg }).notify()
```

Seems to get around the original bug for now.

**Comment by nghuuphuoc** [comment]
You should make a pull request 💯

**Comment by hyperh** [comment]
Will do!

**Comment by hyperh** [comment]
@nghuuphuoc did you get this bug?

```
hotel start
/Users/hl/.npm-packages/bin/hotel start

Options:
  -h, --help     Show help                                             [boolean]
  -v, --version  Show version number                                   [boolean]

Object #<Object> has no method 'execSync'
```

**Comment by nghuuphuoc** [comment]
No. I can add the servers and start them by using my workaround (as mentioned above).
Most commands (add, list, remove, start, stop) work.

**Comment by hyperh** [comment]
I tried just commenting out the line like you @nghuuphuoc, but I run into the same error I described above.

**Comment by adrianmc** [comment]
@hyperh what is your node version? Because: https://github.com/typicode/hotel/issues/62

**Comment by hyperh** [comment]
@adrianmc My node version was `v0.10.40`.  Upgraded to `6.2.2` and the error goes away. Thanks!

I'm getting the expected output now.
```
hotel start
Started http://localhost:2000
```
