### ISSUE TITLE
Not working a proxy to Chrome on OS X

### ISSUE THREAD

**Issue by nooks** [typicode/hotel#113]
In Safari, it works.
![2016-07-27 2 52 57](https://cloud.githubusercontent.com/assets/824669/17159399/a53da56e-53a5-11e6-9459-b9df44caeb23.png)
![2016-07-27 2 53 27](https://cloud.githubusercontent.com/assets/824669/17159400/a95f9e68-53a5-11e6-97be-08544f09d2fa.png)

**Comment by nooks** [comment]
Do not use plug-in ZenMate VPN
Problem fixed

**Comment by typicode** [comment]
@nooks Great, thanks for the update.

If someone else encounter this issue, a thing to remember is that you can always use http://localhost:2000/app-name as a fallback.
