### ISSUE TITLE
PHP Server keeps restarting

### ISSUE THREAD

**Issue by matteodem** [typicode/hotel#114]
First, thanks a lot for this awesome package 🎉 Love using readable localhost domains again.

When I use this package with a Symfony 3.0 project (by calling `bin/console server:run -p $PORT`) it starts the server as expected when toggling it on in the web app. It keeps restarting though when I try to toggle it off.

I have the same error with some of my meteor apps, but it usually stops after some attempts.

My question is if there is a way to define what command to run when stopping a server, in case of the PHP server it would be of great help.

**Comment by matteodem** [comment]
Or is it a feature that the server automatically starts when visiting the `*.dev` url?

**Comment by typicode** [comment]
You're welcome :)

> Or is it a feature that the server automatically starts when visiting the *.dev url?

Yes, exactly. It's for 2 reasons:
* To limit usage resource. For example, if you have 20 servers, there's no reason to start them all.
* To avoid having to go to `hotel.dev` each time you need to start a server. You can simply go to `app.dev`.

But if you have a devtool that regularly try to connect to `app.dev`, it will keep it started.

**Comment by matteodem** [comment]
Okay, yeah that totally makes sense. Thanks for answering
