### ISSUE TITLE
Profiles, groups or multiple configs?

### ISSUE THREAD

**Issue by Madd0g** [typicode/hotel#115]
Hi, great tool!

Is it possible to have some sort of separation between services? I have a lot of work stuff I really don't want to see in the hotel list on nights/weekends. 

Is there quick way to switch configs or anything like that?

Thanks

**Comment by skemb321** [comment]
You can write a script that takes hotel names and move them out from servers directory. Then another script for reverting. Or u can just version the files inside servers directory. I will go for versioning it using git.

**Comment by skemb321** [comment]
Sorry bad english

**Comment by typicode** [comment]
Hi @Madd0g,

I would suggest the same as @skemb321. I even wonder if symlinking `~/.hotel/servers` to `~/some/path` or `~/some/other-path` wouldn't be enough.

**Comment by Madd0g** [comment]
Oh great, now I'm imagining a hotel-like manager for symlinks :)

I'll try the suggested methods, thanks
