### ISSUE TITLE
Won't work for latest Meteor 1.4 apps

### ISSUE THREAD

**Issue by THPubs** [typicode/hotel#122]
For my old meteor apps hotel works perfectly. But for new Meteor 1.4 apps,  I get only this :

    => Started proxy.

And the app won't start. Any idea why this is happening?

**Comment by typicode** [comment]
Hi @THPubs,

Thanks for the report, I'm having the same issue too. But I have noticed that if you tell hotel to start it on port 3000, which is `meteor` default port, it works:

```
hotel add -p 3000 'meteor'
```

On the other side, if I try to start `meteor` using a custom port (and without hotel), it doesn't seem to work either:

```
meteor --port=127.0.0.1:4000
[[[[[ ~/my_cool_app ]]]]]                     

=> Started proxy.  
```

So I think it may be related to the way `port` should be set with `meteor` command.
Do you know a way to set the port for `meteor` 1.4 using the CLI?

**Comment by THPubs** [comment]
@typicode Oh I didn't see that. Thanks :-) Looks like it's not a hotel issue so I'm closing this. Just did some investigating and looks like this is a known bug and they are trying a fix : https://github.com/meteor/meteor/issues/7563  :-)

**Comment by typicode** [comment]
Thank you for the update. Hope it gets fixed soon :)

**Comment by THPubs** [comment]
The latest meteor release `1.4.1.3` finally fixed the issue!  :tada:

**Comment by typicode** [comment]
Awesome, thank you for the update!
