### ISSUE TITLE
Front End Fixes

### ISSUE THREAD

**Issue by spentacular** [typicode/hotel#124]
Currently, the front-end has a quick little flash on load/refresh.

![hotel](https://cloud.githubusercontent.com/assets/1043478/17833537/e65a6af2-66e5-11e6-9bdf-d14bc5747bbf.gif)

Before I make a PR, I wanted to make sure the following was okay, as well as if you wanted anything added to it:

- Upgrade to Vue 2.0
- Setup Webpack similar to [Vue CLI Starter](https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js)
- Port `public/index.html` to `front/`, and create components
- Change "Read Me" to "Hotel - version number" to close #97
- Switch to "system" [font stack](http://lab.ejci.net/favico.js/) 

As well, it may be another PR, but with the people using a pinned tab, there could be potential to have a [favicon notification](http://lab.ejci.net/favico.js/) type setup with the number of processes running? I'm not sure if that would be helpful or not.

Let me know if there's anything else to add (or remove) to above and I'd be happy to take care of it.

**Comment by typicode** [comment]
Hi @spentacular,

Thank you for the help :)

> Upgrade to Vue 2.0

Yes, would be a good idea. But for this PR, could you just update deprecated methods (if any) and keep the rest of the code the same?

> "Flash"

Would be great to fix it. I think a flag (`isListFetched=true`) to detect if the first request has been made could do the trick:
https://github.com/typicode/hotel/blob/master/src/front/index.js#L44
https://github.com/typicode/hotel/blob/master/src/front/index.js#L50

Could be worth checking and better to add it globally here:
https://github.com/typicode/hotel/blob/master/src/front/index.js#L127

And have a `isListLoaded` and `isListEmpty` condition here:
https://github.com/typicode/hotel/blob/master/src/daemon/public/index.html#L15

> Setup Webpack similar to Vue CLI Starter

As far as I can remember, I had trouble making it work with `nodemon`. I'd rather keep it the way it is.

> Port public/index.html to front/, and create components

More or less the same as before, tried `vuex` and `components` but based on the UI complexity, I've finally ended with something simpler to work with for me (1 template, 1 vue).

> Change "Read Me" to "Hotel - version number" to close #97

Hmm, a bit unsure about this idea and I'm thinking about closing the issue.

> Switch to "system" font stack

Is the link correct?

> As well, it may be another PR, but with the people using a pinned tab, there could be potential to have a favicon notification type setup with the number of processes running?

I would prefer to keep the default UI minimalist for maintainability (BTW not against third-party UIs :))

**Comment by spentacular** [comment]
Oops, the system font-stack is [here](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/#approach-b). It only puts San Francisco in front of Helvetica, then has a few better fallbacks for Ubuntu/Linux/Windows.

**Comment by typicode** [comment]
Thanks for the link, wasn't aware of this 👍

**Comment by spentacular** [comment]
Closing since #125
