### ISSUE TITLE
Vue.js warnings

### ISSUE THREAD

**Issue by JanStevens** [typicode/hotel#129]
Hello,

New version has following warnings:

```
bundle.js:11071 [Vue warn]: Property or method "uid" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. (found in root instance)
```

I already fixed it in my MR: https://github.com/typicode/hotel/pull/120/commits/9c0a0d2a6e9aa22c4e793acbea48cf269e95dbda

Maybe it can be merged or we can cherry pick the commit?

**Comment by typicode** [comment]
Hi,

Do you still have it with `hotel v0.5.5`? Because I'm not seeing it anymore, so there may be a commit that has fixed it.

**Comment by typicode** [comment]
Ok, found it.
It was because in the output `item.uid` wasn't used.
https://github.com/typicode/hotel/commit/823978b3689dbf115e92a2a472bb5c946d9a52e5

Thanks for raising this bug.
