### ISSUE TITLE
hotel.dev log, not working in safari OS X

### ISSUE THREAD

**Issue by alejandroMA** [typicode/hotel#130]
In the web frontend hotel.dev
I click on the arrow to show the server log on safari, and its doing nothing.

Inspecting the console reveals this error:

> [Vue warn]: Property or method "uid" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. (found in root instance)

chrome works fine, but i almost never use crome on OS X

just installed hotel on my mac 5 min ago:

> ~ $ hotel --version
> 0.5.5

**Comment by typicode** [comment]
Hi @alejandroMA,

Thanks for the heads up, may be related to #129 (I've not tried it on Safari).

**Comment by alejandroMA** [comment]
yea it looks related, thanks the response :)

**Comment by typicode** [comment]
Just released a fix (`v0.5.6`), at least there shouldn't be this warning anymore.
Let me know if it still doesn't work.

**Comment by alejandroMA** [comment]
i updated to 0.5.6, and the warning is gone:

> ~~[Vue warn]: Property or method "uid" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. (found in root instance)~~

however, the log is still not working on safari. theres a new warning:

> TypeError: undefined is not an object (evaluating '_event$target$element.scrollHeight')
> onScroll - bundle.js:8772

**Comment by alejandroMA** [comment]
i submitted a pull request to fix this
#131

**Comment by typicode** [comment]
Published `0.5.7` (can't test on Safari for the moment, but I hope it'll work).
Used `<button />` instead of `<span />`, so it can be accessed with `tab`.

**Comment by alejandroMA** [comment]
@typicode can't do `hotel start` says

> env: node\r: No such file or directory

not even just `hotel`

i'm using OS X el capitan

**Comment by typicode** [comment]
Thank you, got the same error on Linux. I've deprecated this version.
It may be related to the fact that I've exceptionally published it from Windows.

**Comment by alejandroMA** [comment]
Ohhh maybe, hope you can publish from linux or OS X soon :)

**Comment by typicode** [comment]
Re-published from a Linux env and it seems better (`v0.5.8`)

**Comment by alejandroMA** [comment]
`v0.5.8` it works really nicely on OS X, and `hotel.dev` is working perfectly on safari.
The arrow btns now work.
