### ISSUE TITLE
Can't proxy request to localnet (vagrant vm)

### ISSUE THREAD

**Issue by with0out** [typicode/hotel#139]
Related to #102  ?
I'm running **Windows 7**. and I can't seem to let hotel proxy my request to my **vagrant** vm.
Inside the vm, I used create-react-app to create and run an app, and did the same on host.

(I tried both Firefox and Chrome, both configured to use hotel's pac, and hotel.dev loads fine)

I can connect to the app on **host**:
react.dev -> localhost:3000
```
17 Oct 15:52:01 - Resolve react
17 Oct 15:52:01 - Proxy http://react.dev to http://localhost:3000
17 Oct 15:52:01 - Resolve react
...
17 Oct 15:52:01 - Proxy http://react.dev to http://localhost:3000
17 Oct 15:52:01 - Resolve react
17 Oct 15:52:01 - Connect - proxy socket to localhost:3000
```
But it won't let me connect to the **vm**:
yareact.dev -> 192.168.45.67:3000
```
17 Oct 15:53:47 - Resolve yareact
17 Oct 15:53:47 - Proxy http://yareact.dev to http://192.168.45.67:3000
17 Oct 16:03:47 - Resolve yareact
...
17 Oct 16:03:47 - Proxy http://yareact.dev to http://192.168.45.67:3000
17 Oct 16:05:47 - Resolve yareact
17 Oct 16:05:47 - Proxy http://yareact.dev to http://192.168.45.67:3000
17 Oct 16:11:47 - Resolve www.yareact
17 Oct 16:11:47 - Proxy http://www.yareact.dev to http://192.168.45.67:3000
17 Oct 16:13:47 - Resolve www.yareact
17 Oct 16:13:47 - Proxy http://www.yareact.dev to http://192.168.45.67:3000

```
And the browser would show
```Can't proxy request to http://192.168.45.67:3000.```

I can access http://192.168.45.67:3000 directly and the app loads fine.
Am I missing something?
Thanks.

**Comment by with0out** [comment]
My bad, I somehow used proxifier to tunnel node through my socks proxy, so it won't reach my local network...

**Comment by typicode** [comment]
Thank you for the update :+1: and glad you found the issue :)
