### ISSUE TITLE
[FEATURE] HTTP_X_FORWARDED headers

### ISSUE THREAD

**Issue by natrim** [typicode/hotel#144]
Would be nice if the proxy would send FORWARDED to the backend.

HTTP_X_FORWARDED_FOR
HTTP_X_FORWARDED_HOST
HTTP_X_FORWARDED_PORT

(
why:
i use hotel add 'php -S 127.0.0.1:$PORT'
but when i want to redirect to the local url
then $_SERVER['SERVER_PORT'] contains the php port (something like 55885)
and $_SERVER['SERVER_NAME'] contains 127.0.0.1
which means it will redirect to wrong url
having the HTTP_X_FORWARDED allows the application to know the right ip and port
)

**Comment by typicode** [comment]
Hi @natrim,

Good idea :+1:

**Comment by typicode** [comment]
I've configured the proxy to add some headers, it was just an option actually, so you should get more headers now.
It's available in `v0.5.11`.

I couldn't test it, so feedbacks are welcome :)

**Comment by natrim** [comment]
Thanks, works now.
