### ISSUE TITLE
fail to start

### ISSUE THREAD

**Issue by tryer3000** [typicode/hotel#147]
Install hotel with `sudo npm install -g hotel && hotel start` on my notebook(ubuntu 1604).
I got `permission error` from `~/.hotel/.daemon.log`

```bash
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/.hotel_npminstall/node_modules/.1.0.1@arr-flatten/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
```

**Comment by typicode** [comment]
Hi @tryer3000,

What's the version of `node` and `npm`?
How did you install node?

Depending on your Node installation, I would try installing `hotel` without `sudo`: 

```sh
sudo npm rm -g hotel
npm install -g hotel
```

Could you also check permissions in `/usr/lib/node_modules/.hotel_npminstall/node_modules/` for any inconsistencies. You should have the rights to read them at least.

**Comment by typicode** [comment]
Personally, on Ubuntu I'm using https://github.com/creationix/nvm and it works pretty well:

```
nvm install stable
npm install -g hotel
hotel start
```

**Comment by tryer3000** [comment]
Hi, @typicode
I installed node from package manager according the [Doc of NodeJS](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

Here is my environment.
node: v6.9.1
npm: 3.10.8

BTW, nvm helps, Thank you for your advice.

**Comment by Ti-webdev** [comment]
```bash
sudo chown -R $USER: $HOME/.hotel
```

**Comment by LuigiLazzari** [comment]
Hi, I can install hotel just fine, but I get an error on daemon.log:

`2 Feb 10:55:26 - Watching /home/pchiovatto/.hotel/servers
create /home/pchiovatto/.hotel/daemon.pid 22843
2 Feb 10:55:26 - Server listening on port 127.0.0.1:2000
Exiting
Stop daemon
Remove pid file
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/johnsmith/.hotel/servers ENOSPC
    at exports._errnoException (util.js:1023:11)
    at FSWatcher.start (fs.js:1306:19)
    at Object.fs.watch (fs.js:1331:11)
    at createFsWatchInstance (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/hotel/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)`

**Comment by typicode** [comment]
Hi @LuigiLazzari,

It may happen if `.hotel` directory belongs to `root` or if there's not enough space (but I don't think it's that). Have you tried `sudo chown -R $USER: $HOME/.hotel`, this should fix rights issues.

**Comment by LuigiLazzari** [comment]
That fixed it! Thank you very much!

**Comment by typicode** [comment]
Great :)

**Comment by indrakaw** [comment]
I recommend you guys to install npm localy (no sudo) on home dir. Follow this guide: 
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by typicode** [comment]
@indrakaw Good point, I've added this link to the FAQ.
Thanks :)

**Comment by indrakaw** [comment]
@typicode also, if you install NodeJS via `nvm`, no need sudo or extra permission required. 
```
$ which node
/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node
$ which npm
/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm
```

but the [dist one](https://github.com/nodesource/distributions) (like mine), isn't.
```
$ which node
/usr/bin/node
$ which npm
/home/indrakaw/.npm-global/bin/npm
```

I never tried homebrew before, so I don't know.
