### ISSUE TITLE
Adding dotnetcore server to hotel

### ISSUE THREAD

**Issue by rahulmr** [typicode/hotel#148]
I am able to start the server on the localhost with `PORT` env variable from hotel but the `.dev` domain is not responding.

Here is the command I have used  

`hotel add "SET ASPNETCORE_URLS=https://*:%PORT% && dotnet run"`

Or 

`hotel add "SET ASPNETCORE_URLS=http://localhost:%PORT% && dotnet run"`

Output is 

```
Can't connect to server on PORT=59434.
Possible causes:

    Server crashed or timeout of 5000ms exceeded.
    Server isn't listening on PORT environment variable.

Try to reload or check logs.


cmd /c SET ASPNETCORE_URLS=http://localhost:%PORT% && dotnet run 

My.Api (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hosting environment: Production
Content root path: D:\projects\My.Api
Now listening on: http://localhost:59434
Application started. Press Ctrl+C to shut down.
```

**Comment by typicode** [comment]
Hi @rahulmr,

Based on the output, I don't really know why it doesn't work. It's listening on the right PORT and localhost, so there should be no reasons for it not to work.

Could you try adding it with a fixed port (it's to make it easier to debug):
`hotel add "SET ASPNETCORE_URLS=https://*:%PORT% && dotnet run" --port 4000`

Go to `hotel.dev`, start it and open `http://127.0.0.1:4000`.
Does it work?

Could you also edit `c:\Windows\System32\Drivers\etc\hosts` and add:

```
127.0.0.1 myapi.test
```

Then go to `myapi.test:4000`, it's to verify that the server replies if it's accessed with a different host than `localhost`. 

Also I've noticed that there is a `.` in your project name. Can you try setting a different name:

```sh
hotel add "SET ASPNETCORE_URLS=https://*:%PORT% && dotnet run" --name somename
# http://somename.dev
```

**Comment by rahulmr** [comment]
ok, will try n let you know. And thanks for the wonderful package.
