### ISSUE TITLE
How to use remote ip address instead of localhost and 127.0.0.1?

### ISSUE THREAD

**Issue by Redigast13** [typicode/hotel#150]
I want to open hotel that located on remote server. http://{some-ip}:2000 does not work. But if I open localhost:2000 on remote server then everything works fine

**Comment by typicode** [comment]
Hi @Redigast13,

By default, hotel only listens to `127.0.0.1`. To change this edit `~/.hotel/conf.json`:

```js
"host": "0.0.0.0"
```

Then run `hotel stop && hotel start` to restart and you should be able to access hotel dashboard from outside.

**Comment by Redigast13** [comment]
Thank you!
