### ISSUE TITLE
"hotel.dev" domain doesn't work on Windows

### ISSUE THREAD

**Issue by laggingreflex** [typicode/hotel#151]
"hotel.dev" and other "\<project\>.dev" domains don't work on Windows.

Is this achieved by modifying the `hosts` file? On Windows it's in `C:
Windows\System32\drivers\etc\hosts` file but it will require admin privileges, not sure how this is achieved on Mac/*nix but I'm guessing it's doing it through some other way as I couldn't find in the source anywhere modifying hosts file. Is that correct?

**Comment by typicode** [comment]
Hi @laggingreflex,

No need to edit hosts file.

Have you tried this:
https://github.com/typicode/hotel/blob/master/docs/README.md#windows

Or this (if you use Firefox):
https://github.com/typicode/hotel/blob/master/docs/README.md#firefox

**Comment by laggingreflex** [comment]
Thank you! I missed that part. Although the instructions for windows should be changed to this:

Start > "Internet Options" > Connections > LAN settings > "Use automatic configuration script" > Address: "http://localhost:2000/proxy.pac"

(I'll submit a PR shortly)
