### ISSUE TITLE
Ember livereload using TLD's

### ISSUE THREAD

**Issue by evoactivity** [typicode/hotel#153]
Ember runs live reload on a different port and injects this script into the index.html to load the full live reload script.

```javascript
(function() {
 var src = (location.protocol || 'http:') + '//' + (location.hostname || 'localhost') + ':49152/livereload.js?snipver=1';
 var script    = document.createElement('script');
 script.type   = 'text/javascript';
 script.src    = src;
 document.getElementsByTagName('head')[0].appendChild(script);
}());
```

if you're using a TLD it will load http://host.dev:49152/livereload.js?snipver=1 but this won't work with the TLD as hotel doesn't seem to know how to handle the port, when using localhost all works fine but one of the selling points for me was the TLD option (though it is not actually neccessary for me, just a nice QOL enhancement to my work day)

**Comment by typicode** [comment]
Hi @evoactivity,

Could you try forcing `host` to be `localhost` (https://github.com/ember-cli/ember-cli-inject-live-reload)? This way it shouldn't go through hotel.

Also, if I want to reproduce locally, what should I install and run?

**Comment by evoactivity** [comment]
Hi @typicode,

The host option is to configure the websocket the livereload script creates, there is the `liveReloadJsUrl` option, but I'd need to know the port ahead of time as you need the full url there.

To reproduce locally you'll want to install ember-cli and bower

`npm install -g ember-cli`
`npm install -g bower`

then create a new folder for a project and run `ember new myapp` 

then add `ember s` to hotel.

Thanks.

**Comment by typicode** [comment]
Thanks for the steps, I would need to really play with it to understand how it works. Hope to be able to do it in the coming days.

By the way, don't know if this can help, you can set a PORT that hotel will use. For example, with `hotel add -p 4000 'cmd -p $PORT'`, `$PORT` will always be set to `4000`.

**Comment by evoactivity** [comment]
I'll see if that can help, I'm not 100% sure how hotel is currently dealing with the ports as ember uses two different ones, one for the server which serves the app, and one for the livereload service and hotel seems to manage to set them to two different ports automatically.

**Comment by typicode** [comment]
I've done some tests and hotel `v0.5.12` should work with `ember-cli` without extra configuration :)
There's only with `https://host.dev` that there's still an issue with `livereload`.

**Comment by evoactivity** [comment]
Can confirm livereload is working with the .dev domains now. Thanks a lot :)

**Comment by typicode** [comment]
Great thanks for the confirmation :)
You're welcome.

**Comment by clekstro** [comment]
@typicode Just came across this fix after upgrading. Can't thank you enough for this!

**Comment by typicode** [comment]
@clekstro you're welcome :)
