### ISSUE TITLE
Feature: Exit commands

### ISSUE THREAD

**Issue by htkoca** [typicode/hotel#155]
Hello @typicode ,

I looked over the other issue requests and there isn't any other thread, so I'm making one here. Are there any undocumented / future support for exit commands? Sometimes after launching a server, I have to clean up files related to the server, and being able to run commands when a server exits seems like a good idea.

If this is only for bugs, I apologize and you may close this post. 

Thanks,

@htko89

**Comment by typicode** [comment]
Hi @htko89,

It's the right place :)
Personally, I've not encountered this case so often, so there's no plan to add this feature, sorry.

That said, if it's a server you're developping, I would suggest trying to clean things on exit. You can use [exit-hook](https://github.com/sindresorhus/exit-hook) to make it easy.

You can also write temporary files to `/tmp` which is usually cleaned when you restart your machine.

What kind of server is it?
