### ISSUE TITLE
My secure became broken

### ISSUE THREAD

**Issue by rogovdm** [typicode/hotel#157]
After upgrading to 0.5.13 I keep getting rejects on https calls with error «self signed certificate»

**Comment by rogovdm** [comment]
reverting to v0.5.9 fixed my three hour journey.

**Comment by deep-spaced** [comment]
Same here! 0.5.9 works like a charm.

**Comment by typicode** [comment]
Hi,

Could you try setting `http_proxy: false` in `~/.hotel/conf.json`?

**Comment by deep-spaced** [comment]
@typicode That fixed it! Thank you so much!

**Comment by typicode** [comment]
Hi,

Published `v0.7.0` and `HTTP_PROXY` proxy env is now disabled by default as it was causing side effects for some projects.

Adding `HTTP_PROXY` env should be done on a per-server basis with `hotel add --http-proxy-env 'server-cmd'`.
