### ISSUE TITLE
HTTP_PROXY breaks Python requests

### ISSUE THREAD

**Issue by prashnts** [typicode/hotel#164]
Python's `urllib` and by that extension, `requests` libraries do not support [0] parsing proxy `PAC` files, and assume `HTTP_PROXY` is a Proxy server [1].

`0.5.10` added this behaviour, but not sure if it is required, as it potentially breaks other libs too.

[0] https://stackoverflow.com/questions/31528812/how-to-use-proxy-pac-file-for-python-urllib-or-request
[1] https://docs.python.org/2/library/urllib.html#high-level-interface

**Comment by typicode** [comment]
Hi @prashnts,

Didn't thought it would break Python requests, thanks for the heads up. You can disable `http_proxy` globally by editing `~/.hotel/conf.json` and restarting hotel `hotel stop && hotel start`.

Here's the related PR https://github.com/typicode/hotel/pull/134

Maybe it would be better for it to be per-project option and disabled by default.

**Comment by prashnts** [comment]
Thanks! In the meantime, I'd resorted to simply using this environment variable:

```NO_PROXY="localhost"```

in my server's `json` config. I think this can be the easiest way around; and to assist people, it can be put into the `README` that they can do the same, as it won't require any additional work. :)

I feel this should resolve the issue, so I am closing it. Feel free to reopen.
