### ISSUE TITLE
I might be stupid but..

### ISSUE THREAD

**Issue by xavifuefer** [typicode/hotel#171]
can't get it to work!! :( 

I'm on macOS Sierra 10.12.3 and I have the Automatic Proxy Configuration ticked with the URL: `http://localhost:2000/proxy.pac` and I can't get the .dev domains to work... The only other protocol I have ticked is Auto Proxy Discovery (don't know if related). Any help?

**Comment by typicode** [comment]
Hi @xavifuefer,

Can you access http://localhost:2000/? If it works, you can try configuring one of your browser to test https://github.com/typicode/hotel/tree/master/docs#browser-configuration (if you're using Chrome don't forget to fully exit).

You can also check logs `~/.hotel/daemon.log` you should see a request to `proxy.pac`.

For `Auto Proxy Discovery` I don't know if there can be any side effect `Automatic Proxy Configuration`.

**Comment by xavifuefer** [comment]
@typicode obviously it was my bad... it was a human error as always. HolaVPN Chrome extension (a proxy) was intercepting the requests, disabled. :(

**Comment by typicode** [comment]
Thanks for sharing the solution :) and glad you found the issue
