### ISSUE TITLE
Fail to start hotel, even after reinstall of node

### ISSUE THREAD

**Issue by Jonas-lauwers** [typicode/hotel#174]
When I want to start hotel i get this error: 
i added a function to the index.js in  "nmp_modules_folder/hotel/bin/cli" so i can see the bold text, 
all this is done after a complete reinstall of node.js and hotel

> C:\Users\user\Documents\School\Semester 2\Mobile web apps\Exercises\cars>hotel start
> **spawn called
> { '0': 'cmd',
>   '1':
>    [ '/c',
>      'C:\\Users\\user\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\hotel.vbs' ],
>   '2': { stdio: 'ignore', detached: true } }**
> Started http://localhost:2000
> events.js:160
>       throw er; // Unhandled 'error' event
>    
> Error: spawn cmd ENOENT
>     at exports._errnoException (util.js:1022:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3

**Comment by typicode** [comment]
Hi @Jonas-lauwers,

Can you try running just `cmd`?
It seems like it can't find it and that's it's related to `C:\Windows\System32\` not being present in `PATH`.

http://stackoverflow.com/questions/28624686/get-spawn-cmd-enoent-when-try-to-build-cordova-application-event-js85

http://stackoverflow.com/questions/31398380/fatal-error-spawn-cmd-enoent-grunt-serve

**Comment by Jonas-lauwers** [comment]
Hi @typicode,

Thanks for the reply.
Adding `C:\Windows\System32` to my `PATH` fixed it.
