### ISSUE TITLE
.dev to become official gTLD

### ISSUE THREAD

**Issue by productiveme** [typicode/hotel#185]
When using hotel and the proxy with .dev domains, it works OK from the browser most of the time, but when a server to server API is called using the  .dev domain I started getting the myapp.dev domains being resolved to 127.0.53.53 recently. I found this answer from a similar [vagrant-landrush issue:](https://github.com/vagrant-landrush/landrush/issues/103)

> .dev will soon become a official gTLD (with Google as sole applicant, sigh) and ICANN uses 127.0.53.53 to alert administrators of this name collision. In short vagrant.dev shouldn't be used as default domain anymore by landrush, but be replaced by something else.

> Please refer to the following for further details:

> http://icannwiki.org/.dev
> https://www.icann.org/resources/pages/name-collision-2013-12-06-en#127.0.53.53

**Comment by typicode** [comment]
Thanks for the details, at some point maybe default `tld` will have to be changed to something else (I've not yet found something satisfying and `hotel` is taken too).

Meanwhile, you can configure `tld` to avoid problems:
https://github.com/typicode/hotel/tree/master/docs#configuring-local-dev-domains

**Comment by productiveme** [comment]
Thanks, I somehow missed that section in the docs.

**Comment by typicode** [comment]
I've updated docs, it should be more visible this way :)
https://github.com/typicode/hotel/tree/master/docs#configuring-another-tld

**Comment by fengb** [comment]
I believe Google is buying `.dev` to keep it private. Of course, this assumes they're being altruistic and won't change their minds later.

**Comment by bitstrider** [comment]
Got this today trying to access my `.dev`

![ERR_ICANN_NAME_COLLISION](https://i.ytimg.com/vi/VbKSChQtYWo/hqdefault.jpg)

Though it worked again after restarting my computer

**Comment by Sacro** [comment]
Please stop using .dev!

https://chromium-review.googlesource.com/c/chromium/src/+/669923
