### ISSUE TITLE
Issue with Ionic 2

### ISSUE THREAD

**Issue by rashidali05** [typicode/hotel#189]
## Not Working With Ionic

how i add hotel in Ionic App
```
hotel add 'ionic serve' --o app.log
```

Its start ionic local server at http://localhost:8100/
but i setup hotel with .dev tld.

**Comment by nickstark** [comment]
@rashidali05 I'm doing the same thing. Ionic lets you specify a port, so you should update your command to

```
hotel add 'ionic serve -p $PORT' -o app.log
```

There's more information in the [Readme](https://github.com/typicode/hotel#port)

**Comment by typicode** [comment]
yes, @nickstark thank you for the help :)

**Comment by rashidali05** [comment]
** @nickstark ** Thanks Dear its now working..
