### ISSUE TITLE
ERR_ICANN_NAME_COLLISION when pointing to .dev addressed using Chrome

### ISSUE THREAD

**Issue by laggingreflex** [typicode/hotel#193]
This weird bug just started appearing

In chrome it seems I can't use any of the .dev domains - it shows 

<blockquote>
This site can’t be reached

This site on the company, organization or school intranet has the same URL as an external website. 

Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION
</blockquote>

I found this question on SU: https://superuser.com/questions/919278/err-icann-name-collision-when-trying-to-use-localhost-dev-in-chrome

The weird thing is it only just started appearing for me, I was able to use it just fine a couple days ago. And it also works fine in Firefox even now.

**Comment by laggingreflex** [comment]
Restarting chrome fixed it

**Comment by indrakaw** [comment]
K

**Comment by elladze** [comment]
I'm also having problem on a MAC. Re-starting computer and updating system did not help though. Any insight / steps on how to fix problem?

**Comment by laggingreflex** [comment]
This keeps happening to me too. I think I've narrowed it down to following steps to fix it:

1. close all `chrome.exe` processes, or whatever browser you use
2. close all `node.exe` processes, which will terminate hotel daemon 
3. run `hotel start`
4. run `chrome.exe`
