### ISSUE TITLE
Can't find server id: undefined

### ISSUE THREAD

**Issue by lixinliang** [typicode/hotel#194]
I follow your guide and configure proxy setting.

And, it directs the true page,
`http://hotel.dev/` => `localhost:2000`

After that, I start a server, like this:

![image](https://cloud.githubusercontent.com/assets/9375027/26054783/82b5f0dc-39a0-11e7-85f4-d6c85a9f0fb2.png)

My command like this:

![image](https://cloud.githubusercontent.com/assets/9375027/26054944/48bf24e2-39a1-11e7-9567-d2a0d941310d.png)

But, I could not use the short cut url `http://one.dev/`

it returns `Can't find server id: undefined`

Is there any missing step?

**Comment by indrakaw** [comment]
you have to set `$PORT` variable.

**Comment by typicode** [comment]
> But, I could not use the short cut url http://one.dev/

Hi, have you tried `http://blog.dev` instead (or maybe it's a typo)?

**Comment by lixinliang** [comment]
`http://blog.dev` is work.

I would like to use `http://blog.dev` instead of `http://one.dev`.

It's convenient enough for me.
