### ISSUE TITLE
Question: is katon deprecated?

### ISSUE THREAD

**Issue by rstacruz** [typicode/hotel#2]
I see that hotel is basically a cross-platform version of katon. Does this mean katon is deprecated?

**Comment by typicode** [comment]
Good question :)

No, you can still use katon or you can do the switch.

I don't plan to make hotel as feature-packed as katon, so it won't be a full replacement.

For example, hotel won't rely on anything that requires admin privileges. Therefore, there won't be local domains.

Also, I'll try to keep it simpler with less defaults and more explicit options.

In the end, I'd say hotel is for people who prefer a dev utility that does less and is simpler to understand in case of problems.
