### ISSUE TITLE
Hotel runs script but not on random port?

### ISSUE THREAD

**Issue by kirkins** [typicode/hotel#200]
I add a project with:

    hotel add 'json-server --watch db.json'

Then I go to `hotel.dev` when I click on the project that is on I'm forwarded to `http://localhost:38255/` where I'm unable to connect.

But If I go to `localhost:3000` my application is up and running. So I can confirm hotel ran the script but not on the port which it associates with the app.

How can I fix this?

**Comment by typicode** [comment]
Hi @kirkins,

You can use `--port` option:

```
hotel add 'json-server --watch db.json --port $PORT'
```

$PORT will be replaced by the port defined by hotel.

**Comment by kirkins** [comment]
Thanks that fixed it!

**Comment by kirkins** [comment]
@typicode did you encounter issues with the certificate using this?

![untitled](https://user-images.githubusercontent.com/9503662/27256927-df3bee36-5392-11e7-95c5-bb937050b1ea.png)

I want to use it as a workaround for having to setup `https://` while developing a node.js server connected to by a chrome extension.

_I realize this isn't really an error with the program more a chrome issue and wondering if you came across the same issue._

**Comment by fritx** [comment]
@typicode excuse me, can I just leave the $PORT not being specified by hotel?
e.g. hotel add "some cmd" -p "none"
and the program can itself figure out the port to use

**Comment by j-f1** [comment]
If the program looks at the `PORT` environment variable to determine which port to start the server  on, it should work without having to specify the port.
