### ISSUE TITLE
Not stopping Docker containers

### ISSUE THREAD

**Issue by jukefr** [typicode/hotel#209]
Hey, I guess the way Hotel works right now is that is sends some sort of kill signal to the process command when you add.
However when you send such a command to a `docker-compose up` for instance then the console logs get killed but not the Docker containers themselves.

It would be good to add an optionnal parameter to hotel like some sort of **--on-kill** argument where I would for instance pass in `docker-compose down` for my use case.

**Comment by typicode** [comment]
Hi @kjullien,

I think it would be great. Overall Docker support could be improved in Hotel.
Currently, I lack the time to work on it, but I hope to be able to at some point.

**Comment by EduardoRT** [comment]
@kjullien I've got the same issue, maybe a workaround we can make for now is a script that works as an entrypoint or "server" for hotel and does `docker-compose up` and `docker-compose down` on `KILLSIG`?
