### ISSUE TITLE
ERR_ICANN_NAME_COLLISION .dev account

### ISSUE THREAD

**Issue by elladze** [typicode/hotel#215]
I'm having trouble accessing my website created on a local server. I get the message:

"This site can't be reached
This site on the company, organization or school intranet has the same URL as an external website.
Try contacting your system administrator.
ERR_ICANN_NAME_COLLISION"

Any advice/step-step solutions? Note: the URL was firstname.dev but I changed it to firstnamelastname.dev while logged into firstname.dev on local WordPress. Than the next day when I tried to go back in to log in via /wp-admin, I got this message. I've tried both URL's. I have a Mac. Also, it's not working on Safari, Chrome or Firefox.

**Comment by typicode** [comment]
Hi @elladze,

You can configure hotel to use another tld:
https://github.com/typicode/hotel/blob/master/docs/README.md#configuring-another-tld

But I guess in the long run, it would be better to have a specific tld just for hotel rather than `dev`.

**Comment by typicode** [comment]
Closing as now the default domain name is `.localhost`.
