### ISSUE TITLE
Every command, same error - "Should not be run as root, please retry without sudo."

### ISSUE THREAD

**Issue by aadrian** [typicode/hotel#220]
`hotel` shows on Linux (Ubuntu) the following message, independent of the command typed:
`Should not be run as root, please retry without sudo.`

However, it's not running as root, nor is it started with sudo. Also all NPM and `.hotel` files belog to the normal user, **not** root.

The log file `daemon.log` contains no useful hints.

Any idea what else could I try ?

Thank you.

**Comment by indrakaw** [comment]
Try this `which hotel` or install hotel locally.

**Comment by aadrian** [comment]
@indrakaw Thanks for your help. It seems this problem is present only in `zsh`+`oh-my-zsh` . Reverting back to classical `bash` makes the problem disappear. I looks like `oh-my-zsh` breaks just too many applications :( .

**Comment by indrakaw** [comment]
Okay then. 

I'm using `zsh` + `oh-my-zsh` and having no problem. It seems there is a conflict on `oh-my-zsh` plug-ins. Try to disable it.
