### ISSUE TITLE
How to use it with Docker

### ISSUE THREAD

**Issue by aadrian** [typicode/hotel#224]
Hi,

Please add Docker help and some minimal example usage.

Thank you.

**Comment by deep-spaced** [comment]
Just submitted #230 to help out with this. @aadrian, let me know if this clarifies things for you!

**Comment by typicode** [comment]
Good morning. The PR looks very good, thanks a lot @deep-spaced! :)

I've approved it so you can merge it whenever you want or later if you prefer to get some feedbacks from @aadrian first.

**Comment by aadrian** [comment]
@deep-spaced thank you, looks good!

**Comment by deep-spaced** [comment]
Thanks, @aadrian and @typicode! I'd love to go ahead and merge this, but I'm unsure as to how... Doesn't look like I have write access?

**Comment by typicode** [comment]
Sorry, thought it would be sufficient (first time I'm trying it), merging it.
Thanks again :)
