### ISSUE TITLE
How to create local proxy to the same server

### ISSUE THREAD

**Issue by oguzbilgic** [typicode/hotel#231]
Lets say we have `myapp` project which can be accessible with `myapp.dev`. How can I also create another host for the same server/process such as `otherdomain.dev` ?

**Comment by fengb** [comment]
https://github.com/typicode/hotel#proxy

```bash
$ hotel add http://myapp.dev --name otherdomain
```

This creates the config `~/.hotel/servers/otherdomain.json`
```json
{
  "target": "http://myapp.dev"
}
```
