### ISSUE TITLE
Passing hostname to webpack-dev-server

### ISSUE THREAD

**Issue by mimischi** [typicode/hotel#238]
I've just setup a `webpack-dev-server` project via

```
npm install -g vue-cli
vue init webpack hackernews-vue-apollo
```

The config specifies that one can set `process.env.HOST` to override the default `host: localhost`. Is there currently any way to pass that variable from the `hotel` CLI? I was not able to get it working this way.

**Comment by j-f1** [comment]
If you pass `--change-origin` to the `hotel add` command, the `.dev` proxy will rewrite the `Host` header of the request to match the host and port that the server is listening on.

**Comment by mimischi** [comment]
Thanks! This works :)

For reference, using this `hotel add` command resolves the issue:

```bash
hotel add 'yarn run dev --port $PORT' --name hn --change-origin
```
