### ISSUE TITLE
How does $PORT work with Django

### ISSUE THREAD

**Issue by viztor** [typicode/hotel#239]
See above.

**Comment by j-f1** [comment]
Does the information provided in [my PR](https://github.com/typicode/hotel/pull/240) help you?

**Comment by viztor** [comment]
@j-f1 Hi, Jed. Thank you for offering help. 
I have tried the various way to inject $PORT into runserver command, and I'm asking it here as that command provided in your PR **does not work**. 
I'm running it macOS in case that might explain anything. 
Anyhow, thank yo for replying.

**Comment by j-f1** [comment]
Are you using single quotes (`'`) or double quotes (`"`)? In the shell, `$variables` are interpolated if you use double quotes, and since you don’t have the `$PORT` variable defined in your current shell, it gets replaced with an empty string.

**Comment by j-f1** [comment]
@viztor Did you get it to work?

**Comment by westonganger** [comment]
Oh man I just got bit by this single quotes / double quotes business. Thanks @j-f1 that should be mentioned in the readme in bold
