### ISSUE TITLE
Request never ends

### ISSUE THREAD

**Issue by DavidBernal** [typicode/hotel#248]
I install hotel and go to localhost:2000. Web never loads completely:
![image](https://user-images.githubusercontent.com/4368806/33549448-cd6d8376-d8ea-11e7-92c8-00ed00886ec8.png)

OS: windows 10
Node: 8.7.0
NPM: 5.4.2

**Comment by typicode** [comment]
Hi @DavidBernal,

It's actually working as expected. `events` and `output` are server-sent events (SSE).
It's like Web Socket, but simpler and only goes from server to client. Connection is kept open and events are streamed.

The `style.css` 404 worries me more, you don't have style issues?

**Comment by DavidBernal** [comment]
I don't have problems with css, but the instances keeps without appear.
`hotel ls` shows my commands:
![image](https://user-images.githubusercontent.com/4368806/33554403-dfda525c-d8fc-11e7-9a03-55a7385bea6e.png)

But the localhost:2000 continue blank. This is why I thought about the events/output requests.
