### ISSUE TITLE
HTTPS is not working on Chrome 63

### ISSUE THREAD

**Issue by ton212** [typicode/hotel#250]
According to this article [Chrome to force .dev domains to HTTPS via preloaded HSTS](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/).

When trying to access http://hotel.dev, Chrome will redirects to https://hotel.dev, which self-signed certificate is not acceptable in their preload HSTS.

Is Hotel has a plan to change to domain name from .dev to others? Or is there a way I can use .dev for now?

**Comment by ton212** [comment]
This is appeared to affect Safari Version 11.0.2 (13604.4.7.1.3), but not yet on Firefox 57.0.1

**Comment by indrakaw** [comment]
Please read this issue: https://github.com/typicode/hotel/issues/215

**Comment by ton212** [comment]
Oh, thank you. And sorry for missed that section on README.

I am closing this issue so others can join at #215.

**Comment by mehrdaad** [comment]
@indrakaw Do you know how to setup https on .dev domains?
