### ISSUE TITLE
Change .dev domains to .test by default

### ISSUE THREAD

**Issue by yagudaev** [typicode/hotel#252]
Google which owns the .dev TLD has issued a requirement for all domains under this TLD to use HTTPS. This means that hotel redirects to the HTTPS version of the test domain we are using.

https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

We fixed it for our hotel install by changing the `~/.hotel/conf.json` to have a `.test` tld instead of `.dev`.

We should change the defaults in hotel and the documentation to avoid this issue.

The error it produces is also very confusing it says either:

```
ERR_ICANN_NAME_COLLISION
``` 

or 

```
NET::ERR_CERT_AUTHORITY_INVALID
```

**Comment by tiagofscoelho** [comment]
I would suggest to use `.local` instead of `.test`. It has more meaning, no? But definitely this should be fixed :)

**Comment by nickreynke** [comment]
@tiagofscoelho In 1999 the IETF reserved Top Level DNS Names such as `.test`, `.example`, `.invalid` and `.localhost`. Changing `.dev` to `.local` might not be future safe as `.local` is not reserved and might be bought. (Yay, same happened to `.dev`.)

Read more here: https://tools.ietf.org/html/rfc2606#section-2

I'd consider using one of the reserved names described there.

**Comment by fengb** [comment]
`.local` is also used by Bonjour / mdns

**Comment by typicode** [comment]
Good point and thanks for the links 👍  `.localhost` is now the default domain (see also https://github.com/typicode/hotel/issues/218)
