### ISSUE TITLE
hotel status command

### ISSUE THREAD

**Issue by benavern** [typicode/hotel#253]
Hi,

We have the ability to use `stop` and `start` commands, I'd like to have a command `status` just to know if it is running or not, without having to try start/stop so that I'd guess the answer.

is that an easy feature to develop ? 

Thanks in advance
Benjamin

**Comment by j-f1** [comment]
This is included in my PR #237, where you can run `hotel ls`.

**Comment by benavern** [comment]
mmmh ok.

I am not sure I get why this is in `ls` command, that for me is meant to display all the commands registered, but this is ok for me anyway, 'cause I have what I keed :-)

Thank you
