### ISSUE TITLE
Should I use in Production?

### ISSUE THREAD

**Issue by rendelll** [typicode/hotel#254]
Is it possible to use hotel in production? If yes, how should I go about it?

**Comment by indrakaw** [comment]
My recommendation is no. Because, it only works locally and setup it on network would give a lot of deal on dns settings. That's my tough.

**Comment by rendelll** [comment]
Thanks for you input @indrakaw, but I wanted to use it just to manage (start and stop) all my servers (node and rails) in one place. If Hotel is not the most suitable for production, what may you recommend?

**Comment by nchudleigh** [comment]
No do not use it in production

Supervisor (python)
PM2 (node)

Would be better options

**Comment by rendelll** [comment]
Thanks for the suggestions. I checked out PM2 and it's the best choice for me at the moment in my environment.
