### ISSUE TITLE
Rendering broken

### ISSUE THREAD

**Issue by adius** [typicode/hotel#264]
The log doesn't get displayed for me anymore and I get following error:

Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by typicode** [comment]
It should be better, thanks to @houfio fix 👍

**Comment by adius** [comment]
Yes, works again. Thanks!
