### ISSUE TITLE
question: why is katon still in development?

### ISSUE THREAD

**Issue by rstacruz** [typicode/hotel#27]
with the new proxy.pac feature, hotel has now reached feature parity with [katon](https://github.com/typicode/katon).

**Comment by typicode** [comment]
There's still a few things missing that I plan to implement:

* WebSocket support for .dev domains
* https support

**Comment by typicode** [comment]
I've finally updated katon's  ̀README` with a note to switch to hotel. I've added `WebSocket` support and made a few improvements. `https` will be for later :)
