### ISSUE TITLE
View Server Output in the Browser

### ISSUE THREAD

**Issue by KevinSheedy** [typicode/hotel#29]
Feature request. Option to view the server output in the browser, along with the start/stop buttons. This would allow the developer to monitor several server logs in one consolidated view.

Something like an integration with [logio](http://logio.org/)

**Comment by typicode** [comment]
It's planned :)

**Comment by kbariotis** [comment]
@KevinSheedy the way I think about it, is that you can easily integrate any app to log output to logio and then just have hotel manage an instance of that app.

But to increase your request, I would say that If we could completely integrate, at least at first, the output of the command that hotel manages, that could mean that a lot of people could easily stop opening their terminals(including me) to start an app for development, just to have their debugging logs.

How are you thinking of implementing it @typicode. I would love to help.

**Comment by typicode** [comment]
Hi @kbariotis,

Thank you for the help :). I've hacked something a few weeks ago. It's quite simple to expose an API and use Server-Sent Events to get logs.

However for the UI, I don't know how to mimic the terminal scrollbar (when scrollbar is a the bottom it should always be at the bottom, and if the user moves it, it should stay where it is). It would be helpful if you can look for the code snippet that would allow that.

**Comment by kbariotis** [comment]
Hey @typicode, I've tried creating a prototype over Codepen but I couldn't make a nice replication scenario. :P 

Anyway, here's the idea using jQuery:
```javascript

  var scroll = false;
  var $terminal = $('terminal');

  $terminal.on('scroll', function() {

    /* Determine whether we are on bottom or anywhere above */
    if($(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight) {
      scroll = true;
    } else {
      scroll = false;
    }
  });
  
  /* We are inserting logs into the terminal */

  if(scroll) {
    /* If scrollbar was at the bottom, scroll it down since new text has been added */
    $terminal.scrollTop( $section.prop('scrollHeight'));      
  }
```

**Comment by kbariotis** [comment]
BTW, @KevinSheedy, I have found https://github.com/kilianc/rtail which is a replacement for logio and instead of getting logs through direct calls, it inspects the output of the terminal through pipes. That means that you even use it with hotel even out of the box.

You would add a command like this `node server.js 2>&1 | rtail --id "api.myproject.com"` to hotel.

Ref. https://github.com/kilianc/rtail#examples

**Comment by typicode** [comment]
@kbariotis Thank you for the code snipped :+1:

**Comment by typicode** [comment]
It has been released :) Simply click on the `>` icon and you should see logs.
Thank you again for the help and feedback.

**Comment by fritx** [comment]
When I switch among tabs, the output logs just disappeared and became blank.
What's going on? 😕

**Comment by typicode** [comment]
Logs are actually not kept in memory.
I plan to improve that in the next releases as it's a little bit annoying for me too 😅
