### ISSUE TITLE
hotel.localhost no longer works with Chrome & Chromium latest version on Ubuntu

### ISSUE THREAD

**Issue by zimgodo** [typicode/hotel#294]
Hi,

Today after I've updated my Chrome and Chromium browser to the latest stable version, visiting hotel.localhost (including https) gives me the error 

`ERR_CONNECTION_REFUSED`

Only works when I visited via http(s)://localhost:2000

Checking the chrome proxy `chrome://net-internals/#proxy` shows:

```
Use DIRECT connections.
Source: SYSTEM FAILED
```
Firefox and all other browsers works when I visited https://hotel.localhost and http://hotel.localhost

I've also tried removing all extensions, still no dice.

Both Chrome and Chromium browser on same version:
`Version 65.0.3325.181 (Official Build) (64-bit)`

Let me know if you need more info from me regarding this issue.

Thanks

**Comment by subdroid** [comment]
Additional info: Using Chrome/Chromium on Ubuntu 17.10

**Comment by rolfkleef** [comment]
Same for me with Chrome 66.0.3359.170 (Official Build) (64-bit) on Ubuntu 16.04

**Comment by wizbit** [comment]
Chrome 71 on Windows shows this behavior, Chrome 70 was fine.

**Comment by wizbit** [comment]
If you change the port in conf.json from 2000 to 80, it work in Chrome 71 Windows 10

**Comment by townsymush** [comment]
Great thanks

**Comment by rtablada** [comment]
This is popping up in 71 for Mac OS as well. 

Changing to port 80 doesn't work since other services are already running in Mac OS.

**Comment by djeglin** [comment]
Chrome now forces all requests to `*.localhost` to the loopback ip, apparently, completely ignoring any other interface or configuration, which makes this unusable. I might be tempted to use "localmachine" instead

**Comment by zimgodo** [comment]
> Chrome now forces all requests to `*.localhost` to the loopback ip, apparently, completely ignoring any other interface or configuration, which makes this unusable. I might be tempted to use "localmachine" instead

Yup, `.localmachine` works for me as well. I think I will use it as replacement to `.localhost`

**Comment by j-f1** [comment]
`hotel.tw` is also available. Anything with a 3 letter TLD is the same length as `.localhost`.

**Comment by zimgodo** [comment]
> `hotel.tw` is also available. Anything with a 3 letter TLD is the same length as `.localhost`.

`.tw` is reserved tld for Taiwan https://en.wikipedia.org/wiki/.tw

**Comment by zimgodo** [comment]
> IMO this should just use `*.hotel.xyz` and have @typicode own `hotel.xyz`.

same goes to `.xyz` e.g https://gen.xyz/

**Comment by zimgodo** [comment]
I retract my 

> > `hotel.tw` is also available. Anything with a 3 letter TLD is the same length as `.localhost`.
> 
> `.tw` is reserved tld for Taiwan https://en.wikipedia.org/wiki/.tw



> > IMO this should just use `*.hotel.xyz` and have @typicode own `hotel.xyz`.
> 
> same goes to `.xyz` e.g https://gen.xyz/

I retract my previous comments as I din't realize what you were actually meant to say, my apologies.

Although both domains are available, but something tells me we shouldn't.
