### ISSUE TITLE
I'm running on WSL - root is the default user

### ISSUE THREAD

**Issue by MartinMuzatko** [typicode/hotel#299]
Hello!

I'm running on bash on ubuntu on windows, Root is the default user.
Hotel is unusable for me :/

**Comment by FredyC** [comment]
I am running successor https://github.com/jeansaad/chalet/ on WSL2 and it works fine, no requirement for root user.

**Comment by MartinMuzatko** [comment]
yep, latest changes in WSL2 allow creating a user. Consider this fixed :)
