### ISSUE TITLE
hotel tail

### ISSUE THREAD

**Issue by rstacruz** [typicode/hotel#3]
Something like katon's :)

**Comment by typicode** [comment]
This will be one of the differences with katon :)
Mainly, to keep code and CLI simple. So, you'll have to use:

`tail -f /some/path/project.log`

Sorry about that.
If someone wants to build a third-party tool `hotel-tail` (no pun intended) it's possible.

**Comment by rstacruz** [comment]
where is that path?

**Comment by rstacruz** [comment]
In the event of a crash, you get this message:

> Can't connect to server on port 52579 (retry or check logs).

...it'd be nice too to tell us where those logs are stored.

**Comment by rstacruz** [comment]
Also it seems that you should use `-o log.txt` for spitting out log files... something I found out by randomly trying switches mentioned (but not explained) in --help. This should probably be documented.

**Comment by typicode** [comment]
With `v0.3` when a server fails to start, you get logs in the browser :)
It's a little basic for the moment though (doesn't convert ANSI codes).

**Comment by typicode** [comment]
Closing this since it's now possible to view server output in the browser.
