### ISSUE TITLE
How to pass env variables to hotel?

### ISSUE THREAD

**Issue by jarvisaoieong** [typicode/hotel#324]
I've used nvm to run node projects in different version.

So i set the npm scripts as below for convenience

```
"scripts": {
    "start": "$NVM_DIR/nvm-exec node-dev index.js | bunyan -L"
  },
```

I can't set this to absolute path because the project is developed by different people.

When i use `hotel add 'npm start'` to startup the project, it fails as below

![image](https://user-images.githubusercontent.com/195635/48401050-1252e080-e763-11e8-98de-d60e78ef507d.png)

**Comment by j-f1** [comment]
Try including `-e NVM_DIR` in your `hotel add` command.

**Comment by jarvisaoieong** [comment]
It works! 

Oh..I've miss this option. THX so much.
