### ISSUE TITLE
localhost:2000 is blank and "hotel stop" hangs

### ISSUE THREAD

**Issue by leoj3n** [typicode/hotel#36]
If I check out `dd570bd` and run `npm run build && npm link`, then run `hotel start`, the servers in my configuration are listed at `http://localhost:2000/`.

However, if I reset everything and check out `master` and run `npm link`, then run `hotel start`, nothing is displayed on `http://localhost:2000/`. I do see information spit out at the API endpoints `http://localhost:2000/_/servers` and `http://localhost:2000/_/events`.

When testing either checked out commit, running `hotel stop` never completes and the daemon never shuts itself down. I have to manually run: `launchctl unload /Users/leoj/Library/LaunchAgents/hotel.plist`

I tried debugging these issues on my own without much success so for now I will use `dd570bd` and manually unload the plist. I hope you will iron out these bugs soon! Thanks.

**Comment by typicode** [comment]
Yes, thank you for all the testings. `master` is not in a good state and `v0.4.3` is a bad release so I've deprecated it. Sorry for the trouble.

I plan to fix bugs today or tomorrow on `master` and release a little bit later.

**Comment by leoj3n** [comment]
:facepunch: :+1:

**Comment by leoj3n** [comment]
It's working great except Standard failed linting on `npm install` because of an unused variable `conf` in `src/cli/servers.js`. Removing that declaration allowed install to success then `npm link` and good to go. It even starts and stops the daemon properly now. Good work! Thanks for this.

**Comment by typicode** [comment]
Should be good now `v0.4.6` is published, thanks for testing `master`.
