### ISSUE TITLE
Hotel + SSL?

### ISSUE THREAD

**Issue by mgerton** [typicode/hotel#40]
I'm trying to use hotel with a few apps and one in particular requires me to use SSL locally. Does hotel support this at all, or will I need to stick with something like Apache or Nginx?

**Comment by typicode** [comment]
Hi @mgerton,

It's not currently supported.
Are you using a self-signed cert in dev? 
I think it should be possible to use hotel + Apache in conjunction.

**Comment by mgerton** [comment]
Yep, I have a self-signed cert locally. Currently using nginx to run my app (PHP-based) since the built-in PHP dev server doesn't support SSL :cry: 

If I wanted to use hotel on top of something like nginx, how would that work? The documentation mainly specifies servers that are run from the command line rather than webservers like Apache/Nginx that run in daemons. I guess I'm not sure what the start/stop functionality of hotel would do exactly?

That said, for other projects, I've been using it and I enjoy it, so thanks for the work you've done! :smile:

**Comment by typicode** [comment]
> The documentation mainly specifies servers that are run from the command line rather than webservers like Apache/Nginx that run in daemons.

Yes it's not currently possible, but I plan to add support for them.

> That said, for other projects, I've been using it and I enjoy it, so thanks for the work you've done!

Thank you :)

**Comment by typicode** [comment]
> Yes it's not currently possible, but I plan to add support for them.

Available in `v0.4.7` :) just add `s` to `http` and an exception for hotel self-signed cert.
