### ISSUE TITLE
Question about proxy.pac for Chrome

### ISSUE THREAD

**Issue by renatorib** [typicode/hotel#41]
In docs of Proxy, Browser configuration for Chrome, have this instructions

```
google-chrome --proxy-pac-url=http://localhost:2000/proxy.pac
```

Well, I think its a command, right?
I've run this in my terminal, but this command don't exists here
`zsh: command not found: google-chrome`

Don't have any instructions about this case, what I can do?

**Comment by typicode** [comment]
Hi, what's your OS?

**Comment by renatorib** [comment]
OS X

**Comment by renatorib** [comment]
I've setted Automatic Proxy Discovery in Network Preferences > Advanced > Proxies, but didn't work too.

![image](https://cloud.githubusercontent.com/assets/3277185/13260632/12d004d0-da3b-11e5-800d-74605fa64d56.png)
this screenshot language is portuguese, sorry
"Descoberta de Proxy Automática" is Automatic Proxy Discovery.

**Comment by typicode** [comment]
Try the second line in proxies configuration, you'll then have a URL input then enter `http://localhost:2000/proxy.pac`. 

On OS X, chrome path is:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --proxy-pac-url=http://localhost:2000/proxy.pac
```

I'll update the README

**Comment by typicode** [comment]
My bad just realized there was an error in the doc. It's not `Auto Proxy Discovery` but `Automatic Proxy Configuration`. Sorry for that.

**Comment by renatorib** [comment]
It worked! Thanks :)
