### ISSUE TITLE
.dev is a proposed gTLD in ICANN's new expansion program.

### ISSUE THREAD

**Issue by xhs** [typicode/hotel#43]
Should we change *.dev to *.devel?

**Comment by manojlds** [comment]
Or make it a configuration so that people can choose whatever they want.

**Comment by typicode** [comment]
It's an undocumented feature, but you can configure it in `~/.hotel/conf.json`

```json
"tld": "dev"
```

For example, can be changed to:

```json
"tld": "test"
```

Then restart hotel and reload `http://localhost:2000/proxy.pac` in your network settings or browser

```sh
hotel stop
hotel start
open http://hotel.test
```

I'll update the README.

**Comment by typicode** [comment]
It's updated https://github.com/typicode/hotel/blob/master/docs/README.md
