### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by alejonext** [typicode/hotel#44]
The question is quite interesting suppose, I have an app that handles subdomains. And I need to do to run it, how it works?

**Comment by typicode** [comment]
You mean like aliases? `foo.app.dev`, `bar.app.dev` pointing to the same server?

**Comment by alejonext** [comment]
Yes

**Comment by typicode** [comment]
Thank you, I'll see how it can be supported.
Out of curiosity, what are the subdomains used for?

**Comment by hinok** [comment]
@typicode I think that it's crucial for SaaS applications where subdomain represents specific client's application, similiar to how Zendesk or Atlassian work and in general speaking any other saas software.

**Comment by Calyhre** [comment]
It would be great to handle wildcard subdomains too :)
Ex: `hotel add 'npm start' -n '*.example'`

**Comment by typicode** [comment]
I agree. Just a little feedback about hotel's current development, I'm on #29 (you can check the `output` branch) and then I'll switch to subdomains.

**Comment by typicode** [comment]
I've added wildcard subdomains globally (`v0.4.12`). So if you already have `example.dev` you can now also go to `foo.example.dev`.

Thanks everyone for feedback and @alejonext for code suggestion.
