### ISSUE TITLE
Q: Serving a root file for requests, useful in SPA apps

### ISSUE THREAD

**Issue by hinok** [typicode/hotel#49]
Hey!
In SPA application we want to serve a root file - in most cases `/index.html` because routing is handled by SPA application. Is it possible to do that in hotel?
Thanks.

**Comment by typicode** [comment]
Hi @hinok,

It's not included in `hotel`. But you can do it with any static server of your choice, for example:

```sh
npm install -g serve
hotel add 'serve -p $PORT'
```

There are many static servers on http://npmjs.com.

**Comment by hinok** [comment]
My fault..., you're completly right. Routing should be handled by specific server not hotel.
Thanks for the response! I think that isse can be closed ;)

**Comment by typicode** [comment]
No worries, thank you for the feedback :)
