### ISSUE TITLE
hotel stop && hotel start - can't connect to host any more [OS X]

### ISSUE THREAD

**Issue by djeglin** [typicode/hotel#54]
Hi all, 

I've been using Katon for a little while now, but decided to try out Hotel as it is suggested on the main Katon GH page. 

My issue is that after restarting Hotel, I can no longer connect to localhost on port 2000 (getting `ERR_CONNECTION_REFUSED`). Its like Hotel doesn't spin back up properly after stopping. This goes for trying to connect both to `localhost:2000` and to `[project name].test` (had to configure the "test" tld as the latest versions of Chrome have a problem with .dev domains). 

Any help gratefully received.

D

**Comment by typicode** [comment]
Hi @djeglin,

It's a bug, will look into it.
Thank you for the report.

**Comment by typicode** [comment]
I've released `v0.4.8`, you may need to do `hotel stop` before `hotel start` to clean stuff.
And by the way, welcome to `hotel` :)

**Comment by djeglin** [comment]
Seems to have worked :) Thanks for the quick solve, and for the welcome :)
