### ISSUE TITLE
Can't connect to server on port XXXXX

### ISSUE THREAD

**Issue by julianorafael** [typicode/hotel#56]
I'm having a problem when trying to access one of the projects through the .dev domain. The output that appears in the browser is as follows:

```
Can't connect to server on port 45355. Server crashed or timeout of 5000ms exceeded. Retry or check logs.
sh -c npm start


> pomodoro-app@0.0.0 start /home/julianorafael/Development/projects/pomodoro-app
> cross-env NODE_ENV=development node server.dev.js

Starting server...

Server started
Listening at localhost:3000
```

**Comment by typicode** [comment]
Hi @julianorafael,

It's because `pomodoro-app` isn't listening to the `PORT` environment provided by hotel.
If you edit `server.dev.js`, you should be good.

Here are some explanations and code examples [here](https://github.com/typicode/hotel#port).

**Comment by julianorafael** [comment]
All right, rookie mistake. I the project was on the port 3000 and the hotel was listening on a random port. Thanks for the help.

**Comment by typicode** [comment]
You're welcome :)

**Comment by chrise86** [comment]
I keep getting this issue too:

```
Can't connect to server on port 49835. Server crashed or timeout of 5000ms exceeded. Retry or check logs.
sh -c rails s -p $PORT

=> Booting Puma
=> Rails 4.2.6 application starting in development on http://localhost:49835
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:49835
```

**Comment by typicode** [comment]
@chrise86 it seems to be listening on the right port.
If you wait a little bit and reload the page with the error, does it work?
If you go directly to http://localhost:49835 does it work?

**Comment by chrise86** [comment]
Waiting and reloading doesn't, going directly does

**Comment by typicode** [comment]
Last time I checked with Rails it worked. I will give it another try. 

As a fallback, you can use `http://localhost:2000` and `http://localhost:2000/my-app` in place of `hotel.dev` and `app.dev`.

Could you paste daemon logs `~/.hotel/daemon.log` when you try to access your app on a `.dev` domain?

**Comment by chrise86** [comment]
`http://localhost:2000/my-app` also doesn't work.

Both `hotel.dev` and `localhost:2000` work, though.

**Comment by chrise86** [comment]
Nothing appears in the log when I access the app either :-/

**Comment by typicode** [comment]
Could you try running the following commands and paste the output:

```
$ hotel add -n test 'python -m SimpleHTTPServer $PORT`
$ open http://test.dev
$ tail -n 100 ~/.hotel/daemon.log
```

The idea is to know if it's related to the server or hotel. You're on OS X?

**Comment by chrise86** [comment]
Yeh OSX.

```
1 Apr 14:38:04 - Created /Users/chrisedwards/.hotel/servers/test.json
1 Apr 14:38:04 - Add server id: test cmd: undefined port: 50962
1 Apr 14:38:12 - test has started
1 Apr 14:38:13 - Proxy http://test.dev to http://127.0.0.1:50962
1 Apr 14:38:13 - Proxy http://test.dev to http://127.0.0.1:50962
```

**Comment by typicode** [comment]
Thanks, so there might be something related to the Rails server.
And if you do this:

```
project$ hotel add -n test 'rails s -p $PORT'
project$ open http://project.dev
project$ tail -n 100 ~/.hotel/daemon.log
```

What's the output?

**Comment by chrise86** [comment]
```
1 Apr 14:53:31 - Created /Users/chrisedwards/.hotel/servers/testrails.json
1 Apr 14:53:31 - Add server id: testrails cmd: undefined port: 51261
1 Apr 14:53:44 - testrails has started
1 Apr 14:53:47 - testrails has stopped
1 Apr 14:53:48 - testrails has started
1 Apr 14:53:51 - testrails has stopped
```

**Comment by typicode** [comment]
Interesting, did it stopped 2 times by itself or did you use the switch from `hotel.dev`?

**Comment by chrise86** [comment]
Hm. Did it itself :-/

**Comment by typicode** [comment]
No worries.
I don't really understand right now why it doesn't work, sorry.

At least, I would have expected some logs. I'll check that later, maybe add some logs and try to reproduce on my machine.

**Comment by typicode** [comment]
@chrise86 may be related to #70

**Comment by jalada** [comment]
Sorry @typicode. I looked through the issues to see if there was an existing one, but obviously not closely enough :)

**Comment by typicode** [comment]
@jalada no worries about that :) I may not have found it myself if I wasn't reading all the issue.

**Comment by dominikmueller** [comment]
I can confirm this problem. I'm using ruby with sinatra.
Everything worked/works fine when i'm using the **WEBrick** server but as soon as i install the rubygem '**thin**' i'm getting the same problem (-> after installing thin, sinatra starts the thin webserver).

Console output when running with WEBrick (working):
````
2016-04-06 14:35:13] INFO  WEBrick 1.3.1
[2016-04-06 14:35:13] INFO  ruby 2.2.3 (2015-08-18) [x86_64-darwin14]
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick
[2016-04-06 14:35:13] INFO  WEBrick::HTTPServer#start: pid=52759 port=4567
^C== Sinatra has ended his set (crowd applauds)
````

vs.

Console output when running with thin (not working)
````
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
^CStopping ...
````

Maybe it helps in the debugging process ;)

I'm using WEBrick for now.

**Comment by typicode** [comment]
Just in case others encounter the same issue, @jalada has found a workaround. You need to bind to `127.0.0.1`.
There's usually an option for that, for example with Rails it looks like this:

```
hotel add 'rails s -p $PORT -b 127.0.0.1'
```

However, feel free to report issues with other servers.
