### ISSUE TITLE
Toggle not working in Safari 9.1

### ISSUE THREAD

**Issue by activatedgeek** [typicode/hotel#64]
I am able to access `hotel.dev`. But on clicking the toggle, it doesn't work on `Safari 9.1`.

Here is the stack trace.
<img width="380" alt="screen shot 2016-04-03 at 1 09 57 am" src="https://cloud.githubusercontent.com/assets/3909933/14228643/ea5a8a62-f938-11e5-81d1-33810fb299ef.png">

It looks like the `fetch` library is missing (from the stack trace above). It works in Chrome though.

Any known bugs here?

**Comment by typicode** [comment]
Thank you, just forgot to add `fetch` polyfill. Will fix it right now.

**Comment by activatedgeek** [comment]
Awesome!

**Comment by typicode** [comment]
Should be good `v0.4.10`
