### ISSUE TITLE
Convert ANSI logs output to HTML

### ISSUE THREAD

**Issue by kbariotis** [typicode/hotel#65]
![screen shot 2016-04-04 at 13 09 00](https://cloud.githubusercontent.com/assets/605742/14244896/79ed9740-fa66-11e5-8218-747041816f9f.png)

Regarding #29

**Comment by typicode** [comment]
@kbariotis Thanks for the heads up!
I forgot to handle ANSI, as a quick fix I'll strip them and will look for something better later.

**Comment by typicode** [comment]
Should be better with `v0.4.11` ;)

**Comment by kbariotis** [comment]
There are a few modules out there that could possibly help like 

* https://github.com/drudru/ansi_up
* https://github.com/rburns/ansi-to-html

**Comment by typicode** [comment]
Thank you for the links :)

**Comment by typicode** [comment]
Just released in `v0.4.19`. Thank you @kbariotis and @jalada for the help.
