### ISSUE TITLE
Projects?

### ISSUE THREAD

**Issue by zekenie** [typicode/hotel#67]
Hi there!

Loving this tool. Seriously considering adding it to my toolset and possibly contributing. Do you have any plans to implement projects? Let's say I have 3 servers that are all related. I might want to have a page for them. Then have another page for another 4 servers that are related?

Thanks!

**Comment by typicode** [comment]
Hi @zekenie,

Thank you for the feedback and suggestion. No plan for such feature right now, sorry, but I would be interested in understanding the need or problem(s) with the current UI.

You would like to be able to have projects page for better readability or for some other reasons too?

**Comment by zekenie** [comment]
Thanks for getting back to me! It's more that I jump around from project to project and typically want several servers to all be on or all be off. It's really nice to be able to see the stdout of the relevant processes. My terminal tabs get crazy with lots of projects and hierarchy would be awesome.

**Comment by typicode** [comment]
You're welcome. Thank you for the feedback on the stdout.

I wouldn't worry much about being sure that they're all started. 
If you have `.dev` domains enabled, hotel will start them for you on the first request as needed.

For example:

1. `server-one`, `server-two` and `server-three` are stopped
2. You make a request to http://server-one.dev
3. Hotel will start `server-one`
4. `server-one` makes a request to `server-two.dev` and `server-three.dev`
5. Hotel will automatically start `server-two.dev` and `server-three.dev` and forward the request

But for stopping all of them, it's true there's no way to stop a group of server at once.

Don't know how your projects are organised but maybe a `procfile` or similar would help in starting a group of servers.

Anyway, thanks again. And I'm always interested in what works or not, so if anyone feels there's something not convenient with hotel let me know :)
