### ISSUE TITLE
Hotel doesn't detect IPv6 listeners

### ISSUE THREAD

**Issue by jalada** [typicode/hotel#70]
The default Puma + Rails 5 on El Capitan configuration means that Puma binds to `locahost:PORT` which (in Puma land) resolves to to `[::1]:PORT` ([More information about this 'behaviour' in Puma / TCPServer](https://github.com/puma/puma/issues/782)). However hotel expects it to bind to `127.0.0.1:PORT`, and so returns an error saying that the app didn't start (when it did).

A couple of workarounds:

1. Pass `-b 127.0.0.1` to `rails server`. 
2. Remove `::1  localhost` mapping from `/etc/hosts` (not ideal).
3. Add a puma config to force it to listen to `127.0.0.1` not `localhost`.

This might be a wont-fix, but I thought I'd report it anyway :)

**Comment by typicode** [comment]
Hey, thanks a lot for the link, it may explain https://github.com/typicode/hotel/issues/56#issuecomment-204374604.

I wonder if simply making `hotel` forward requests to `localhost:PORT` instead of `127.0.0.1:PORT` by default wouldn't be better actually.

**Comment by typicode** [comment]
I've updated the `README` with the first workaround.

**Comment by typicode** [comment]
For the moment, I don't think it should be fixed in hotel since it might get fixed in Puma or `TCPServer`. Closing it for now.
