### ISSUE TITLE
After restart .dev domains won't load

### ISSUE THREAD

**Issue by benjamincharity** [typicode/hotel#71]
First off, thanks for Hotel; I've been looking for something just like this for quite some time.

- - - 

My .dev domains never seem to connect now (they were working).

```
// Actions:
$ hotel stop
$ hotel start
// now `http://localhost:2000/` works
// but `hotel.dev` never connects
```

I tried stopping, reinstalling (`npm install -g hotel`) and starting again with no luck.

Just checked and my Automatic Proxy Configuration is still selected.

My `conf.json`:

```
{
  "port": 2000,
  "host": "127.0.0.1",
  "timeout": 5000,
  "tld": "dev"
}
```
Any ideas?

**Comment by typicode** [comment]
Hmm, I would try to stop/start the network to force reloading `proxy.pac`, make sure that `hotel` is running before.

`localhost:2000/proxy.pac` is requested once, usually when you configure your network/browser to use it. So, if at some moment it wasn't available then even if you start hotel later, your network/browser won't be aware that it should route `.dev` domains to `hotel`.

You can see if `proxy.pac` was requested in `~/.hotel/daemon.log`.

**Comment by benjamincharity** [comment]
That did it!

- `$ hotel start`
- Disabled wifi
- Enabled wifi
- Visit `hotel.dev`

Thanks for the fast response!

**Comment by typicode** [comment]
You're welcome :) I've updated docs to emphasize this point.
