### ISSUE TITLE
Custom subdomain fire custom launch script?

### ISSUE THREAD

**Issue by benjamincharity** [typicode/hotel#81]
I saw that subdomain support was released 🔥 . Now I am wondering to what extent I can use them.

We spin up our project based on environment variables..

```
# spin up local development
$ gulp serve --env local

# build against our staging environment
$ gulp serve --env staging

# build against production environment
$ gulp serve --env production
```

Currently I have three separate domains set up to emulate this:
![screen shot 2016-04-18 at 8 29 50 am](https://cloud.githubusercontent.com/assets/270193/14604106/d5d4c248-053f-11e6-8901-5c1f946ceb30.png)

My hope is that I can do something more like this:

```
# local.client.dev
$ gulp serve --env local

# staging.client.dev
$ gulp serve --env staging

# production.client.dev
$ gulp serve --env production
```

Is this possible or are subdomains more about pointing to different servers etc?

**Comment by typicode** [comment]
It's possible :)

```
$ hotel add 'gulp serve --env local' -n local.client
$ hotel add 'gulp serve --env staging' -n staging.client
$ hotel add 'gulp server --env production' -n production.client
```

**Comment by benjamincharity** [comment]
Ahh too damn easy! Thanks!
