### ISSUE TITLE
Sometimes it seems impossible to turn a server off and keep it off.

### ISSUE THREAD

**Issue by benjamincharity** [typicode/hotel#82]
I have a server running:

![screen shot 2016-04-18 at 8 39 20 am](https://cloud.githubusercontent.com/assets/270193/14604346/1901b296-0541-11e6-80d0-dd1dddd2a184.png)

I click the toggle and it visually turns off but restarts again automatically in about 2 seconds. I have tried stopping/starting hotel. Wanted to see if anyone had some thoughts before I resorted to rebooting my machine.

(gif is sped up a bit)
![hotelbug mp4](https://cloud.githubusercontent.com/assets/270193/14604452/b83b08b2-0541-11e6-9d6f-26326d189400.gif)

**Comment by typicode** [comment]
Hmm... not seeing it on the GIF but since `hotel` automatically starts a server when there's a request to it, I would check if there's not a tool still making requests to `bower-demos.dev`.

It's the case with some front-end tools that keep trying to connect using WebSocket or HTTP when the server is down.

**Comment by benjamincharity** [comment]
> hotel automatically starts a server when there's a request to it

Well that would make sense. I use browser sync which definitely could be sending that request. I had previously closed the tab so assumed it had been stopped.

I will have to look into it to see what might be happening. I think this is the most likely cause so will close this issue out and do some investigation.

Thanks!

**Comment by intermundos** [comment]
I have the same issue with browser-sync, if left open, it keeps restarting the project. 

Any ideas on this issue? Where to look?

Thanks in advance.

**Comment by benjamincharity** [comment]
I eventually had to switch to using ngrok.io. That solution doesn't offer any help or tooling around starting/stoping servers, but it did allow me to use custom domains for all of my local projects (which was my primary need). You just reserve a couple subdomains inside ngrok and set up one config file. Pretty simple.

Hotel is a pretty sweet tool, but it's pretty rare these days for me to work on a front-end project that doesn't use some form of browsersync.

**Comment by intermundos** [comment]
Thank you for your reply and advise. 

The problem comes out only when you stopped the project in hotel.dev, but haven't closed window in browser. I think the issue is minor, considering your stopped working on project anyway. Closing tab in browser will do the trick.
