### ISSUE TITLE
javascript error in browser 

### ISSUE THREAD

**Issue by bagbee** [typicode/hotel#84]
Hi,

I have installed Hotel and started it:
```
$ npm install -g hotel
$ hotel start
```
then I got in my browser on http://localhost:2000/
```
bundle.js:16 
Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js!./../../node_modules/sass-loader/index.js!./style.scss"
``` 

os: ubuntu 15.04
npm: 3.7.3
node: 5.7.0

thoughts?

**Comment by typicode** [comment]
I get the error too. There must have been some error with the latest release.
Until it's fixed, I would suggest installing `npm i -g hotel@0.4.13`

**Comment by bagbee** [comment]
ok. thanks

**Comment by typicode** [comment]
It should be good now (`v0.4.15`).
Thank you for reporting this issue :+1:
