### ISSUE TITLE
Toggle not working on Safari 9.0

### ISSUE THREAD

**Issue by rmp135** [typicode/hotel#92]
Hotel v0.4.18
Attempting to switch the toggle in Safari 9.0 results in the following error.
![screen shot 2016-04-27 at 20 33 52](https://cloud.githubusercontent.com/assets/3882803/14865645/7183f99c-0cb7-11e6-80e8-7e35a8df3b0e.png)
If you'd like any more information, let me know.

**Comment by typicode** [comment]
I'll check that :) thank you.
Seems to be an issue with fetch (I'm using https://github.com/github/fetch).

**Comment by typicode** [comment]
Should be good now (`v0.4.20`)
