### ISSUE TITLE
Framework Detection

### ISSUE THREAD

**Issue by Gaelan** [typicode/hotel#98]
It would be very cool if Hotel knew about common web frameworks and could use a default configuration for each (similar to how Heroku does it). This way, we could just do `hotel add` and have things "just work." For example, `hotel add` in a folder with a `Gemfile` that contained the string `gem "rails"` could default to `hotel add 'rails server -p $PORT -b 127.0.0.1' -o log/development.log`.

**Comment by typicode** [comment]
That's a nice idea!

However I don't think it should be the responsibility of hotel to do that. I prefer to keep it agnostic and focused. Also, every time a server would be added, a server command changed, that would mean a release.

Instead, I think a CLI or small wrapper would be great. Maybe something like that (don't pay attention to the name it's just for the example):

```sh
$ npm install -g hotel framework-detector-cli
$ hotel add `frameword-detector-cli`
```

If you happen to write one, feel free to create a PR to add it to the third-party tools:
https://github.com/typicode/hotel#third-party-tools
